export const agents = [
  {
    id: 1,
    name: 'INSIGHTING ENGINE',
    task: 'Market Trends',
    metric: '89% optimized',
    metricValue: 89,
    progressPercent: 89,
    status: 'active',
    activities: [
      'Activity analysis: 94%',
      'Activity optimization: 87%',
      'Activity connections: 91%',
      'Activity recovery: 78%',
      'Activity comprehensive: 85%',
    ],
  },
  {
    id: 2,
    name: 'PRODUCT ENGINE',
    task: 'Roadmap v3.1, Features: 14',
    metric: 'Feature 14 Active',
    metricValue: 78,
    progressPercent: 78,
    status: 'active',
    activities: [
      'Activity analysis: 82%',
      'Activity optimization: 76%',
      'Activity connections: 88%',
      'Activity recovery: 71%',
      'Activity comprehensive: 79%',
    ],
  },
  {
    id: 3,
    name: 'DESIGN ENGINE',
    task: '3D Mockups, Webframes',
    metric: '94% complete',
    metricValue: 94,
    progressPercent: 94,
    status: 'active',
    activities: [
      'Activity analysis: 96%',
      'Activity optimization: 92%',
      'Activity connections: 89%',
      'Activity recovery: 95%',
      'Activity comprehensive: 91%',
    ],
  },
  {
    id: 4,
    name: 'FRONTEND ENGINE',
    task: 'Code generation React/Next.js',
    metric: '118 Deployments',
    metricValue: 118,
    progressPercent: 85,
    status: 'active',
    activities: [
      'Activity analysis: 88%',
      'Activity optimization: 84%',
      'Activity connections: 90%',
      'Activity recovery: 81%',
      'Activity comprehensive: 86%',
    ],
  },
  {
    id: 5,
    name: 'BACKEND ENGINE',
    task: 'API status GraphQL',
    metric: '96% Uptime',
    metricValue: 96,
    progressPercent: 96,
    status: 'active',
    activities: [
      'Activity analysis: 97%',
      'Activity optimization: 94%',
      'Activity connections: 92%',
      'Activity recovery: 89%',
      'Activity comprehensive: 95%',
    ],
  },
  {
    id: 6,
    name: 'DB ENGINE',
    task: 'Schema optimized, SQL',
    metric: '4,278 Data',
    metricValue: 4278,
    progressPercent: 72,
    status: 'active',
    activities: [
      'Activity analysis: 75%',
      'Activity optimization: 70%',
      'Activity connections: 78%',
      'Activity recovery: 68%',
      'Activity comprehensive: 73%',
    ],
  },
  {
    id: 7,
    name: 'QA ENGINE',
    task: 'Test codes, R3 Q4 Coverage',
    metric: '59%',
    metricValue: 59,
    progressPercent: 59,
    status: 'active',
    activities: [
      'Activity analysis: 62%',
      'Activity optimization: 55%',
      'Activity connections: 64%',
      'Activity recovery: 51%',
      'Activity comprehensive: 58%',
    ],
  },
]

export const engineNodes = [
  { id: 1, name: 'Insighting Engine', x: -5.0, y: 0.8, z: 0.0, metric: '89%' },
  { id: 2, name: 'Product Engine', x: -3.3, y: 1.4, z: 0.05, metric: '78%' },
  { id: 3, name: 'Design Engine', x: -1.6, y: 1.8, z: -0.05, metric: '94%' },
  { id: 4, name: 'Frontend Engine', x: 0.0, y: 2.0, z: 0.0, metric: '118' },
  { id: 5, name: 'Backend Engine', x: 1.7, y: 1.8, z: 0.05, metric: '96%' },
  { id: 6, name: 'DB Engine', x: 3.3, y: 1.3, z: -0.05, metric: '4,278' },
  { id: 7, name: 'QA Engine', x: 5.0, y: 0.7, z: 0.0, metric: '59%' },
]

export const conversationMessages = [
  { speaker: 'DR. CHEN', text: 'Optimize the user login flow on Backend...' },
  { speaker: 'AI NEXUS', text: 'Understood. Optimizing Backend & Frontend, generating QA tests.' },
  { speaker: 'DR. CHEN', text: 'Run full regression on the updated modules.' },
  { speaker: 'AI NEXUS', text: 'Regression initiated. Estimated completion: 4 minutes.' },
  { speaker: 'DR. CHEN', text: 'Check the Design Engine output for consistency.' },
  { speaker: 'AI NEXUS', text: 'Design Engine at 94%. All mockups passing validation.' },
  { speaker: 'DR. CHEN', text: 'Scale the database connections for peak load.' },
  { speaker: 'AI NEXUS', text: 'DB Engine scaling initiated. Current throughput: 4,278 ops/sec.' },
]

export const logMessages = [
  { message: 'Optimize the user login flow on Backend...', type: 'info' },
  { message: 'Optimize State Merging select task query based...', type: 'info' },
  { message: 'Optimize the chat engine for Bottleneck...', type: 'info' },
  { message: 'Optimize Infrastructure Management setup...', type: 'info' },
  { message: 'Frontend/Optimizing User Login UI & Backend & Frontend...', type: 'info' },
  { message: 'Machine learning Execution Shutdown stress test...', type: 'info' },
  { message: '[CODE] Frontend AI-ED training on the test...', type: 'code' },
  { message: 'Frontend Hybrid testing request: Frontend Application...', type: 'info' },
  { message: 'Backend API optimization: GraphQL resolver caching...', type: 'info' },
  { message: 'DB Engine: Schema migration v3.2 applied successfully...', type: 'code' },
  { message: 'QA Engine: Test suite R3-Q4 running 847 test cases...', type: 'info' },
  { message: 'Design Engine: Webframe generation batch 12 complete...', type: 'info' },
  { message: 'Product Engine: Feature 14 dependency graph updated...', type: 'info' },
  { message: 'Insighting Engine: Market trend analysis cycle 89...', type: 'info' },
  { message: '[CODE] Neural pipeline synchronization checkpoint...', type: 'code' },
]

export const agentStatuses = [
  { name: 'Dr. Chen Status', status: 'ACTIVE' },
  { name: 'Backend Status', status: 'ACTIVE' },
  { name: 'Augment Status', status: 'ACTIVE' },
  { name: 'AI Flights', status: 'ACTIVE' },
]

export const akinformsData = [
  { label: 'Semantics', value: 60 },
  { label: 'Context', value: 80 },
  { label: 'Communication', value: 45 },
  { label: 'Authority', value: 70 },
  { label: 'Skill', value: 55 },
]
